name: Build Windows Installer

on:
  push:
    branches: [ main ] # Trigger on push to the main branch
  pull_request:
    branches: [ main ] # Optional: Trigger on pull requests to main
  workflow_dispatch: # Allow manual triggering

jobs:
  build:
    runs-on: windows-latest # Use a Windows runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10' # Specify your desired Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller # Install PyInstaller

    - name: Run PyInstaller
      run: pyinstaller MyMedicalApp.spec
      # This creates the bundled app in dist/salle_attente_cabinet_medical

    - name: Set up Inno Setup
      uses: Mincka/inno-setup-action@v1
      # This action downloads and adds ISCC (Inno Setup Compiler) to the PATH

    - name: Compile Inno Setup script
      run: iscc setup.iss
      # This uses the setup.iss script to create the installer
      # The output installer (CabinetMedicalSetup.exe) will be in the 'dist' folder (defined in setup.iss)

    - name: Upload Installer Artifact
      uses: actions/upload-artifact@v4
      with:
        name: CabinetMedicalSetup-${{ github.sha }} # Name the artifact uniquely
        path: dist/CabinetMedicalSetup.exe # Path to the generated installer
