name: Build Windows Installer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [created]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'
        check-latest: true
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
      continue-on-error: false
    
    - name: Install Inno Setup
      run: |
        choco install innosetup --no-progress -y
      continue-on-error: false
    
    - name: Build with PyInstaller
      run: |
        pyinstaller app.spec --noconfirm --clean
      continue-on-error: false
    
    - name: Create Inno Setup Script
      run: |
        echo "[Setup]" > installer.iss
        echo "AppName=Cabinet Medical" >> installer.iss
        echo "AppVersion=0.1" >> installer.iss
        echo "DefaultDirName={autopf}\Cabinet Medical" >> installer.iss
        echo "DefaultGroupName=Cabinet Medical" >> installer.iss
        echo "OutputBaseFilename=CabinetMedical_Setup" >> installer.iss
        echo "Compression=lzma" >> installer.iss
        echo "SolidCompression=yes" >> installer.iss
        echo "UninstallDisplayIcon={app}\app.exe" >> installer.iss
        echo. >> installer.iss
        echo "[Files]" >> installer.iss
        echo "Source: ""dist\app\*""; DestDir: ""{app}""; Flags: recursesubdirs" >> installer.iss
        echo "Source: ""assets\*""; DestDir: ""{app}\assets""; Flags: recursesubdirs" >> installer.iss
        echo "Source: ""medical_office.db""; DestDir: ""{app}""; Flags: onlyifdoesntexist" >> installer.iss
        echo. >> installer.iss
        echo "[Icons]" >> installer.iss
        echo "Name: ""{group}\Cabinet Medical""; Filename: ""{app}\app.exe""" >> installer.iss
        echo "Name: ""{commondesktop}\Cabinet Medical""; Filename: ""{app}\app.exe""" >> installer.iss
      shell: cmd
    
    - name: Build Installer
      run: |
        "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" installer.iss
      continue-on-error: false
    
    - name: Upload Installer Artifact
      uses: actions/upload-artifact@v4
      with:
        name: CabinetMedical-Installer
        path: Output/CabinetMedical_Setup.exe
        retention-days: 5
        if-no-files-found: error
        
    - name: Upload to Release
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v2
      with:
        files: Output/CabinetMedical_Setup.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
