name: Build Windows Installer

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering from GitHub UI

env:
  PYTHON_VERSION: 3.9

permissions:
  contents: write

jobs:
  build:
    name: Build Windows EXE
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    
    - name: Verify icon file
      run: |
        echo "Current directory: $(Get-Location)"
        echo "Icon file exists: $(Test-Path app_icon.ico)"
        if (Test-Path app_icon.ico) {
          echo "Icon file size: $((Get-Item app_icon.ico).Length) bytes"
        } else {
          echo "WARNING: Icon file not found!"
          echo "Files in directory:"
          Get-ChildItem
        }
      shell: powershell
        
    - name: Cache Python dependencies
      id: cache-dependencies
      uses: actions/cache@v3
      with:
        path: ./.cache/pip
        key: ${{ runner.os }}-python-${{ env.PYTHON_VERSION }}-${{ hashFiles('requirements.txt') }}
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Install PyInstaller
      run: |
        pip install pyinstaller
        
    - name: Build Application Directory
      run: |
        # Setting the icon path with double quotes to handle spaces
        $iconPath = "$((Get-Location).Path)\app_icon.ico"
        Write-Host "Using icon at path: $iconPath"
        
        # Check if icon exists before running PyInstaller
        if (-not (Test-Path $iconPath)) {
          Write-Host "ERROR: Icon file not found at $iconPath"
          exit 1
        }
        
        # Run PyInstaller with the icon path
        pyinstaller --onedir --windowed --name MedicalOfficeApp `
          --hidden-import babel.numbers `
          --hidden-import babel.dates `
          --hidden-import json `
          --hidden-import sqlite3 `
          --hidden-import logging `
          --exclude-module matplotlib.tests `
          --exclude-module numpy.random.tests `
          --exclude-module pandas.tests `
          --exclude-module unittest `
          --exclude-module doctest `
          --icon="$iconPath" `
          --noupx `
          --clean `
          app.py
      shell: powershell
        
    - name: Download Inno Setup
      run: |
        curl -L -o innosetup.exe "https://files.jrsoftware.org/is/6/innosetup-6.2.2.exe"
      shell: bash

    - name: Install Inno Setup
      run: |
        ./innosetup.exe /VERYSILENT /SUPPRESSMSGBOXES /NORESTART /SP-
        echo "C:\Program Files (x86)\Inno Setup 6" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      shell: powershell

    - name: Create Simple Installer Images
      run: |
        # Create simple bitmap files for installer using PowerShell
        Add-Type -AssemblyName System.Drawing
        
        # Create main wizard image (simpler version)
        $bitmap = New-Object System.Drawing.Bitmap 164, 314
        $graphics = [System.Drawing.Graphics]::FromImage($bitmap)
        $graphics.Clear([System.Drawing.Color]::White)
        $bitmap.Save("installer_image.bmp", [System.Drawing.Imaging.ImageFormat]::Bmp)
        $graphics.Dispose()
        $bitmap.Dispose()
        
        # Create small wizard image (simpler version)
        $bitmap = New-Object System.Drawing.Bitmap 55, 58
        $graphics = [System.Drawing.Graphics]::FromImage($bitmap)
        $graphics.Clear([System.Drawing.Color]::LightBlue)
        $bitmap.Save("installer_small.bmp", [System.Drawing.Imaging.ImageFormat]::Bmp)
        $graphics.Dispose()
        $bitmap.Dispose()
        
        # Verify images exist
        Get-Item "installer_image.bmp", "installer_small.bmp" | Select-Object Name, Length
      shell: powershell

    - name: Create Inno Setup Script (Simplified)
      run: |
        $innoScript = @"
[Setup]
AppName=Medical Office App
AppVersion=1.0
AppPublisher=Dr. Mohammed Mehdi Bouchene
AppPublisherURL=https://bakha-pneumo.netlify.app/
DefaultDirName={autopf}\Medical Office App
DefaultGroupName=Medical Office App
OutputDir=.\dist
OutputBaseFilename=MedicalOfficeSetup
Compression=lzma
SolidCompression=yes
WizardStyle=modern
UninstallDisplayIcon={app}\MedicalOfficeApp.exe
DisableDirPage=no
SetupIconFile=app_icon.ico
WizardImageFile=installer_image.bmp
WizardSmallImageFile=installer_small.bmp

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source:
